/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_NativeDemo */

#ifndef _Included_org_example_NativeDemo
#define _Included_org_example_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_NativeDemo
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_NativeDemo_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
